In [111]:
import pandas as pd
import numpy as np
import sklearn.datasets as datasets
import os


from sklearn.datasets import make_classification
from sklearn import metrics
from sklearn import cluster, datasets, mixture
from sklearn.neighbors import kneighbors_graph
from sklearn.preprocessing import StandardScaler
from itertools import cycle, islice
from mpl_toolkits.mplot3d import Axes3D


from numpy import where
from numpy import unique

from sklearn.decomposition import PCA
from sklearn.decomposition import KernelPCA

In [112]:
df = pd.read_csv(os.path.expanduser("~/Desktop/FinalData.csv"))

In [113]:
X = df[["Movehub Rating","Purchase Power","Health Care","Pollution","Quality of Life",
        "Crime Rating","Congestion Level","Education","Annual Temperature"]]

In [114]:
X_reduced = PCA(n_components=9).fit_transform(X)

In [115]:
from sklearn.cluster import KMeans
startup = np.array([[60,30,50,30,50,33,22,40,47],[60,60,55,30,80,55,13,35,47],[90,60,55,60,80,33,44,60,70],
           [79,46,66,44,60,41,27,47,29],[90,56,70,56,34,55,33,34,50],[79,56,77,33,55,50,33,55,70],
          [60,46,66,33,52,30,44,55,59],[90,50,45,33,60,41,15,47,70]])
model = KMeans(n_clusters=8, n_init=100, init=startup)
model.fit(X_reduced)
clusters = unique(model.labels_)
df["Cluster"] = model.labels_
list = [[-9999,11.25,50,80,8.61,85.7,9,-9999,-9999]]
print(df.mean(axis = 0))
for i in range(len(list[0])):
    if list[0][i] == -9999:
        list[0][i] = df.mean(axis = 0)[i]
prediction = model.predict(list)[0]

Movehub Rating        79.772696
Purchase Power        46.510980
Health Care           66.321275
Pollution             44.884020
Quality of Life       60.021324
Crime Rating          41.607892
Congestion Level      27.357843
Education             47.432598
Annual Temperature    59.777549
lat                   29.753758
lng                    2.053508
Cluster                3.205882
dtype: float64


<ipython-input-115-e3d9fb3d9480>:6: RuntimeWarning: Explicit initial center position passed: performing only one init in k-means instead of n_init=100
  model.fit(X_reduced)


In [116]:
for cluster in clusters:
    row_ix = where(model.labels_ == cluster)
    print(row_ix)
    if cluster == prediction:
        targetCluster = row_ix

(array([  0,   2,   5,   6,   8,  14,  15,  16,  18,  19,  21,  23,  26,
        30,  33,  40,  41,  44,  46,  47,  48,  49,  54,  60,  61,  62,
        64,  66,  67,  68,  77,  78,  79,  80,  83,  84,  88, 100, 112,
       114, 115, 117, 118, 119, 125, 131, 132, 139, 141, 165, 168]),)
(array([  3,  22,  29,  32,  34,  35,  45,  56,  65,  69,  81,  93,  97,
       107, 108, 126, 127, 186]),)
(array([ 63,  71, 101, 136, 143, 145, 150, 151, 153, 160, 161, 175, 176,
       177, 178, 195, 197, 199, 201]),)
(array([ 10,  17,  43,  53,  57,  70,  73,  94,  98, 110, 116, 120, 128,
       130, 134, 142, 152, 158, 167, 170, 184, 191, 194, 196]),)
(array([ 31,  36,  51, 103, 104, 106, 122, 123, 148, 157, 164, 171]),)
(array([  1,   4,   7,   9,  11,  12,  13,  20,  24,  25,  28,  37,  59,
        75,  86,  92,  99, 133, 146, 149, 156, 163, 182, 190, 202]),)
(array([ 74,  76,  87,  89,  90,  95, 109, 111, 113, 121, 124, 129, 135,
       138, 147, 159, 162, 166, 172, 173, 174, 179, 180, 183, 185, 

In [117]:
print(targetCluster)

(array([  0,   2,   5,   6,   8,  14,  15,  16,  18,  19,  21,  23,  26,
        30,  33,  40,  41,  44,  46,  47,  48,  49,  54,  60,  61,  62,
        64,  66,  67,  68,  77,  78,  79,  80,  83,  84,  88, 100, 112,
       114, 115, 117, 118, 119, 125, 131, 132, 139, 141, 165, 168]),)
